name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Brian5m1th
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      - name: Commit e Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando cobrinha 🐍"
          branch: output
